# Generated by Django 5.1.9 on 2025-05-16 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(default='', verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('subtitulo', models.CharField(max_length=255)),
                ('cuerpo', models.TextField(blank=True, default='')),
                ('info_adicional', models.TextField(blank=True, default='')),
                ('icono_url', models.CharField(blank=True, default='', max_length=255)),
                ('publicado', models.BooleanField(default=False)),
                ('tipo', models.CharField(choices=[('blog', 'Blog'), ('faq', 'FAQ'), ('legal', 'Legal'), ('info', 'Información'), ('min_section', 'Sección mínima')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contenido',
                'verbose_name_plural': 'Contenidos',
                'db_table': 'contenido',
            },
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=12, verbose_name='Calle')),
                ('ciudad', models.CharField(max_length=30, verbose_name='Ciudad')),
                ('provincia', models.CharField(max_length=100, verbose_name='Provincia')),
                ('pais', models.CharField(max_length=100, verbose_name='país')),
                ('codigo_postal', models.CharField(max_length=10, verbose_name='Código Postal')),
            ],
            options={
                'verbose_name': 'Dirección',
                'verbose_name_plural': 'Direcciones',
                'db_table': 'direccion',
            },
        ),
        migrations.CreateModel(
            name='PoliticaPago',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('descripcion', models.TextField(default='', verbose_name='Descripción')),
                ('deducible', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deposito_seguridad', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Depósito de seguridad')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Politica Pago',
                'verbose_name_plural': 'Politicas Pagos',
                'db_table': 'politica_pago',
            },
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(default='', verbose_name='Descripción')),
                ('fecha_inicio', models.DateTimeField(verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateTimeField(verbose_name='Fecha de fin')),
                ('activo', models.BooleanField(default=False)),
                ('descuento_pct', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Descuento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'promoción',
                'verbose_name_plural': 'Promociones',
                'db_table': 'promocion',
            },
        ),
        migrations.CreateModel(
            name='TipoPenalizacion',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(default='', verbose_name='Descripción')),
                ('valor_tarifa', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor Tarifa')),
                ('Tipo_Tarifa', models.CharField(choices=[('porcentaje', 'Porcentaje'), ('fijo', 'Fijo'), ('importe_dia', 'Importe')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo Penalización',
                'verbose_name_plural': 'Tipos Penalizacines',
                'db_table': 'tipo_penalizacion',
            },
        ),
        migrations.CreateModel(
            name='GrupoCoche',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, default='', verbose_name='Descripción')),
                ('edad_minima', models.PositiveSmallIntegerField(default=23)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_Categoria_GrupoCoche', to='api.categoria')),
            ],
            options={
                'verbose_name': 'Grupo Coche',
                'verbose_name_plural': 'Grupos Coches',
                'db_table': 'GrupoCoche',
            },
        ),
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('telefono', models.CharField(max_length=20, verbose_name='Telefono')),
                ('icono_url', models.CharField(blank=True, default='', max_length=200)),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direccion_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='get_Direccion_Lugar', to='api.direccion', verbose_name='Dirección')),
            ],
            options={
                'verbose_name': 'Lugar',
                'verbose_name_plural': 'Lugares',
                'db_table': 'lugar',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_recogida', models.DateTimeField(verbose_name='Fecha de recogida')),
                ('fecha_devolucion', models.DateTimeField(verbose_name='Fecha de devolucion')),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('notas_internas', models.CharField(blank=True, default='', max_length=250)),
                ('precio_dia', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Precio por día en el momento de reservar')),
                ('precio_impuestos', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio total con impuestos')),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Impuestos totales')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lugar_devolucion_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='get_LugarDevolucion_Reserva', to='api.lugar')),
                ('lugar_recogida_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='get_LugarRecogida_Reserva', to='api.lugar')),
                ('politica_pago_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.politicapago')),
                ('promocion_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.promocion')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='get_User_Reserva', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Reseva',
                'verbose_name_plural': 'Resevas',
                'db_table': 'reserva',
            },
        ),
        migrations.CreateModel(
            name='Penalizacion',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(verbose_name='Fecha')),
                ('descripcion', models.TextField(default='', verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reserva_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='get_Reserva_Penalizacion', to='api.reserva', verbose_name='Reserva')),
                ('tipo_penalizacion_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='get_TipoPenalizacion_Penalizacion', to='api.tipopenalizacion', verbose_name='Tipo de penalización')),
            ],
            options={
                'verbose_name': 'Penalización',
                'verbose_name_plural': 'Penalizaciones',
                'db_table': 'penalizacion',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False, verbose_name='ID')),
                ('segundo_conductor', models.BooleanField(default=False)),
                ('tipo_documento', models.CharField(choices=[('dni', 'DNI'), ('nie', 'NIE'), ('pasaporte', 'Pasaporte')], max_length=50, verbose_name='Tipo de documento')),
                ('numero_documento', models.CharField(blank=True, max_length=12, null=True, verbose_name='Número de documento')),
                ('imagen_carne', models.ImageField(blank=True, null=True, upload_to='carne/imagenes', verbose_name='Imagen')),
                ('telefono', models.CharField(max_length=20, verbose_name='Telefono')),
                ('activo', models.BooleanField(default=False)),
                ('verificado', models.BooleanField(default=False)),
                ('registrado', models.BooleanField(default=False)),
                ('rol', models.CharField(choices=[('cliente', 'Cliente'), ('admin', 'Administrador'), ('empresa', 'Empresa')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direccion_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='get_Direccion_Usuario', to='api.direccion', verbose_name='Dirección')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='get_User_Usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=100, unique=True, verbose_name='Matricula de vehiculo')),
                ('marca', models.CharField(max_length=100, verbose_name='Marca de vehiculo')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo de vehiculo')),
                ('anio', models.PositiveIntegerField()),
                ('color', models.CharField(max_length=50)),
                ('num_puertas', models.PositiveSmallIntegerField()),
                ('num_pasajeros', models.PositiveSmallIntegerField()),
                ('capacidad_maletero', models.IntegerField()),
                ('disponible', models.BooleanField(default=True, verbose_name='Disponible')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('notas_internas', models.CharField(blank=True, default='', max_length=250)),
                ('combustible', models.CharField(choices=[('Gasolina', 'Gasolina'), ('Diesel', 'Diesel'), ('Híbrido', 'Híbrido'), ('Eléctrico', 'Eléctrico')], max_length=20)),
                ('precio_dia', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Precio al día')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_Categoria_Cehiculo', to='api.categoria')),
                ('grupo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_GrupoCoche_Vehiculo', to='api.grupocoche')),
            ],
            options={
                'verbose_name': 'Grupo Coche',
                'verbose_name_plural': 'Grupos Coches',
                'db_table': 'vehiculo',
            },
        ),
        migrations.AddField(
            model_name='reserva',
            name='vehiculo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='get_Vehiculo_Reserva', to='api.vehiculo'),
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(verbose_name='Fecha')),
                ('tipo_servicio', models.CharField(max_length=200, verbose_name='Tipo servicio')),
                ('coste', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Coste')),
                ('descripcion', models.TextField(default='', verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehiculo_id', models.ForeignKey(db_column='vehiculo', on_delete=django.db.models.deletion.RESTRICT, related_name='get_Vehiculo_Mantenimiento', to='api.vehiculo', verbose_name='Vehiculo')),
            ],
            options={
                'verbose_name': 'Mantenimiento',
                'verbose_name_plural': 'Mantenimientos',
                'db_table': 'matenimiento',
            },
        ),
        migrations.CreateModel(
            name='ImagenVehiculo',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='vehiculo/imagenes', verbose_name='Imagen')),
                ('portada', models.BooleanField(blank=True, default=False, null=True, verbose_name='¿Imagen Principal?')),
                ('vehiculo_id', models.ForeignKey(db_column='vehiculo', on_delete=django.db.models.deletion.CASCADE, related_name='get_Vehiculo_ImagenVehiculo', to='api.vehiculo', verbose_name='Vehiculo')),
            ],
            options={
                'verbose_name': 'Imagen Vehiculo',
                'verbose_name_plural': 'Imagenes Vehiculos',
                'db_table': 'imagen_vehiculo',
            },
        ),
        migrations.CreateModel(
            name='PoliticaIncluye',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100, verbose_name='Item')),
                ('no_incluye', models.BooleanField(default=False)),
                ('politica_pago_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='get_PoliticaPago_PoliticaIncluye', to='api.politicapago', verbose_name='Politica de pago')),
            ],
            options={
                'verbose_name': 'Politica Incluye',
                'verbose_name_plural': 'Politicas Incluyes',
                'db_table': 'politica_incluye',
                'constraints': [models.UniqueConstraint(fields=('politica_pago_id', 'item'), name='unique_politica_item')],
            },
        ),
        migrations.CreateModel(
            name='ReservaConductor',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('principal', 'Principal'), ('segundario', 'Segundario')], max_length=20)),
                ('reserva_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='get_Reserva_ReservaConductor', to='api.reserva', verbose_name='Reserva')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='get_User_ReservaConductor', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Reserva Conductor',
                'verbose_name_plural': 'Reservas Conductores',
                'db_table': 'reserva_conductor',
                'constraints': [models.UniqueConstraint(fields=('user_id', 'reserva_id'), name='unique_user_reserva')],
            },
        ),
        migrations.CreateModel(
            name='PoliticaPenalizacion',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_previas', models.PositiveSmallIntegerField(verbose_name='Horas previas')),
                ('politica_pago_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='get_PoliticaPago_PoliticaPenalizacion', to='api.politicapago', verbose_name='Politica de pago')),
                ('tipo_penalizacion_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='get_TipoPenalizacion_PoliticaPenalizacion', to='api.tipopenalizacion', verbose_name='Tipo de penalización')),
            ],
            options={
                'verbose_name': 'Politica Penalización',
                'verbose_name_plural': 'Politicas Penalizacines',
                'db_table': 'politica_penalizacion',
                'constraints': [models.UniqueConstraint(fields=('politica_pago_id', 'tipo_penalizacion_id'), name='unique_politica_tipo_penalizacion')],
            },
        ),
        migrations.CreateModel(
            name='TarifaVehiculo',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateTimeField(verbose_name='Fecha de fin')),
                ('precio_dia', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Precio por día')),
                ('vehiculo_id', models.ForeignKey(db_column='vehiculo', on_delete=django.db.models.deletion.CASCADE, related_name='get_Vehiculo_TarifaVehiculo', to='api.vehiculo', verbose_name='Vehiculo')),
            ],
            options={
                'verbose_name': 'Tarifa Vehiculo',
                'verbose_name_plural': 'Tarifas Vehiculos',
                'db_table': 'tarifa_vehiculo',
                'indexes': [models.Index(fields=['vehiculo_id', 'fecha_inicio', 'fecha_fin'], name='idx_tarifa_periodo')],
                'constraints': [models.UniqueConstraint(fields=('vehiculo_id', 'fecha_inicio'), name='unique_tarifa')],
            },
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(condition=models.Q(('estado', 'confirmada')), fields=['fecha_recogida', 'fecha_devolucion'], name='idx_fechas_confirmadas'),
        ),
    ]
