# Generated by Django 5.1.9 on 2025-05-31 15:34

from django.db import migrations, models
import django.core.validators
from decimal import Decimal


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipopenalizacion',
            name='valor_tarifa',
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal('0.00'),
                help_text="Valor de la tarifa según el tipo: para 'porcentaje' es el % a aplicar (ej: 25.00 para 25%), para 'fijo' es el importe fijo en euros, para 'importe_dia' es el importe por día de alquiler",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal('0.00'))],
                verbose_name='Valor de la tarifa'
            ),
        ),
    ]
