# Generated by Django 5.1.9 on 2025-05-31 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_promocion_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenido',
            name='tipo',
            field=models.CharField(choices=[('blog', 'Blog'), ('faq', 'FAQ'), ('legal', 'Legal'), ('info', 'Información'), ('mini_section', 'Sección mínima'), ('testimonial', 'Testimonio')], max_length=20, verbose_name='Tipo'),
        ),
    ]
