# Generated by Django 5.1.9 on 2025-07-11 16:32

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lugares', '0001_initial'),
        ('politicas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='extras/', verbose_name='Imagen')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Extra',
                'verbose_name_plural': 'Extras',
                'db_table': 'extras',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ReservaConductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('principal', 'Principal'), ('secundario', 'Secundario')], default='principal', help_text='Rol del conductor en la reserva', max_length=20, verbose_name='Rol')),
            ],
            options={
                'verbose_name': 'Conductor de reserva',
                'verbose_name_plural': 'Conductores de reserva',
                'db_table': 'reserva_conductor',
            },
        ),
        migrations.CreateModel(
            name='ReservaExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Extra de reserva',
                'verbose_name_plural': 'Extras de reserva',
                'db_table': 'reserva_extra',
                'ordering': ['extra__nombre'],
            },
        ),
        migrations.CreateModel(
            name='Penalizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Importe')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('tipo_penalizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalizaciones', to='politicas.tipopenalizacion')),
            ],
            options={
                'verbose_name': 'Penalización',
                'verbose_name_plural': 'Penalizaciones',
                'db_table': 'penalizacion',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_recogida', models.DateTimeField(verbose_name='Fecha de recogida')),
                ('fecha_devolucion', models.DateTimeField(verbose_name='Fecha de devolución')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('precio_dia', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Precio por día')),
                ('precio_impuestos', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Precio impuestos')),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Precio total')),
                ('metodo_pago', models.CharField(choices=[('tarjeta', 'Tarjeta'), ('efectivo', 'Efectivo')], default='tarjeta', help_text='Método de pago utilizado para la reserva', max_length=20, verbose_name='Método de pago')),
                ('importe_pagado_inicial', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Importe pagado inicial')),
                ('importe_pendiente_inicial', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Importe pendiente inicial')),
                ('importe_pagado_extra', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Importe pagado extra')),
                ('importe_pendiente_extra', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Importe pendiente extra')),
                ('notas_internas', models.TextField(blank=True, null=True, verbose_name='Notas internas')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lugar_devolucion', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='devoluciones', to='lugares.lugar')),
                ('lugar_recogida', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='recogidas', to='lugares.lugar')),
                ('politica_pago', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='reservas', to='politicas.politicapago')),
                ('promocion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to='politicas.promocion')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'db_table': 'reserva',
                'ordering': ['-created_at'],
            },
        ),
    ]
