# Generated by Django 5.1.9 on 2025-07-11 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservas', '0001_initial'),
        ('vehiculos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='usuario',
            field=models.ForeignKey(on_delete=models.SET(-1), related_name='reservas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reserva',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='reservas', to='vehiculos.vehiculo'),
        ),
        migrations.AddField(
            model_name='penalizacion',
            name='reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalizaciones', to='reservas.reserva'),
        ),
        migrations.AddField(
            model_name='reservaconductor',
            name='conductor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conducciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reservaconductor',
            name='reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conductores', to='reservas.reserva'),
        ),
        migrations.AddField(
            model_name='reservaextra',
            name='extra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_extra', to='reservas.extras'),
        ),
        migrations.AddField(
            model_name='reservaextra',
            name='reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extras', to='reservas.reserva'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['fecha_recogida', 'fecha_devolucion'], name='idx_reserva_fechas'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['estado', 'created_at'], name='reserva_estado_9cac5c_idx'),
        ),
        migrations.AddIndex(
            model_name='penalizacion',
            index=models.Index(fields=['reserva', 'tipo_penalizacion'], name='penalizacio_reserva_b00fc7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reservaconductor',
            unique_together={('reserva', 'conductor')},
        ),
        migrations.AlterUniqueTogether(
            name='reservaextra',
            unique_together={('reserva', 'extra')},
        ),
    ]
