# Generated by Django 5.1.9 on 2025-08-23 20:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lugares', '0001_initial'),
        ('politicas', '0002_politicapago_tarifa'),
        ('reservas', '0003_alter_reserva_usuario'),
        ('vehiculos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='numero_reserva',
            field=models.CharField(blank=True, db_index=True, help_text='Número único de reserva con formato M4Y + 6 dígitos', max_length=15, null=True, unique=True, verbose_name='Número de reserva'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['numero_reserva'], name='idx_reserva_numero'),
        ),
    ]
