# Generated by Django 5.1.9 on 2025-09-10 20:35

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0005_rename_precio_impuestos_to_iva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='iva',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='IVA'),
        ),
    ]
