# Generated by Django 5.1.9 on 2025-09-10 21:18

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0006_alter_reserva_iva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='iva',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='IVA incluido en el precio total (solo para visualización)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='IVA (simbólico)'),
        ),
    ]
