services:

  # Servicio para el frontend React
  frontend:
    build:
      context: ./frontend  # Ruta al Dockerfile del frontend
      
    command: npm start
    volumes:
      - ./frontend:/usr/app
      - /usr/app/node_modules
    ports:
      - "3000:3000"  # Mapea el puerto 3000 del contenedor al puerto 3000 de la máquina local
    depends_on:
      - backend  # Asegúrate de que el backend esté listo
    networks:
      - mfy-network


  # Servicio para el backend Django
  backend:
    build:
      context: ./backend  # Ruta al Dockerfile del backend

    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"  # Mapea el puerto 8000 del contenedor al puerto 8000 de la máquina local
    depends_on:
      - db  # Espera a que la base de datos esté lista
    environment:
      - DEBUG=True
    networks:
      - mfy-network


  # Servicio para la base de datos (Mariadb en este caso)
  db:
      image: mariadb:latest
      container_name: mariadb
      restart: always
      environment:
        MYSQL_DATABASE: mobilityforyou
        MYSQL_USER: admin
        MYSQL_PASSWORD:  adminpassword
        MYSQL_ROOT_PASSWORD: rootpassword
      ports:
        - "3307:3306"  # expone 3306 del contenedor en el puerto 3307 del host
      volumes:
        - db_data:/var/lib/mysql

# Volúmenes para la base de datos
volumes:
  db_data:

# Redes para conectar los servicios
networks:
  mfy-network:
    driver: bridge

