# Usa una imagen oficial de Python como base
FROM python:3.9-slim

# Actualiza los repositorios e instala dependencias necesarias
RUN apt-get update && apt-get install -y \
    pkg-config \
    default-libmysqlclient-dev \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# Establece el directorio de trabajo en el contenedor
WORKDIR /app

# Copia el archivo de requerimientos e instala las dependencias de Python
COPY requirements.txt /app/
RUN pip install --upgrade pip && pip install -r requirements.txt

# Copia el resto del código fuente al contenedor
COPY . /app/

# Expone el puerto (por ejemplo, 8000) para Django
EXPOSE 8000

# Comando para iniciar la aplicación Django
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
