# Usa una imagen oficial de Python como base
FROM python:3.12-slim

# Establece el directorio de trabajo en el contenedor
WORKDIR /app

# Copia el archivo de requisitos y lo instala
COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

# Copia el código del backend
COPY . /app/

# Expone el puerto 8000 para el servidor Django
EXPOSE 8000

# Comando para iniciar el servidor cuando se ejecute el contenedor
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
