# Generated by Django 5.1.9 on 2025-06-22 13:29

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_contrato', models.CharField(max_length=50, unique=True, verbose_name='Número de contrato')),
                ('fecha_firma', models.DateField(blank=True, null=True, verbose_name='Fecha de firma')),
                ('condiciones', models.TextField(blank=True, null=True, verbose_name='Condiciones')),
                ('url_pdf', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL del PDF')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('firmado', 'Firmado'), ('anulado', 'Anulado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='reservas.reserva')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'db_table': 'contrato',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['numero_contrato'], name='contrato_numero__ddbd27_idx'), models.Index(fields=['estado', 'fecha_firma'], name='contrato_estado_ae644c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(max_length=50, unique=True, verbose_name='Número de factura')),
                ('fecha_emision', models.DateField(verbose_name='Fecha de emisión')),
                ('base_imponible', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Base imponible')),
                ('iva', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='IVA')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total')),
                ('url_pdf', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL del PDF')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('emitida', 'Emitida'), ('anulada', 'Anulada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='reservas.reserva')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'db_table': 'factura',
                'ordering': ['-fecha_emision'],
                'indexes': [models.Index(fields=['numero_factura'], name='factura_numero__d7656a_idx'), models.Index(fields=['estado', 'fecha_emision'], name='factura_estado_220e3f_idx')],
            },
        ),
    ]
