# Generated by Django 5.1.9 on 2025-07-11 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facturas_contratos', '0001_initial'),
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='reservas.reserva'),
        ),
        migrations.AddField(
            model_name='factura',
            name='reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='reservas.reserva'),
        ),
        migrations.AddIndex(
            model_name='contrato',
            index=models.Index(fields=['numero_contrato'], name='contrato_numero__ddbd27_idx'),
        ),
        migrations.AddIndex(
            model_name='contrato',
            index=models.Index(fields=['estado', 'fecha_firma'], name='contrato_estado_ae644c_idx'),
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['numero_factura'], name='factura_numero__d7656a_idx'),
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['estado', 'fecha_emision'], name='factura_estado_220e3f_idx'),
        ),
    ]
