# Generated by Django 5.1.9 on 2025-07-15 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturas_contratos', '0002_add_archivo_pdf_fields'),
        ('facturas_contratos', '0002_initial'),
    ]

    operations = [
    ]
