# Generated by Django 5.1.9 on 2025-06-22 13:25

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Calle')),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad')),
                ('provincia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Provincia')),
                ('pais', models.CharField(default='España', max_length=100, verbose_name='País')),
                ('codigo_postal', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Código postal inválido', regex='^\\d{4,10}$')], verbose_name='Código Postal')),
            ],
            options={
                'verbose_name': 'Dirección',
                'verbose_name_plural': 'Direcciones',
                'db_table': 'direccion',
                'ordering': ['ciudad', 'provincia'],
            },
        ),
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitud')),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitud')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Número de teléfono inválido', regex='^\\+?1?\\d{9,15}$')], verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('icono_url', models.CharField(blank=True, max_length=200, null=True, verbose_name='Icono')),
                ('info_adicional', models.TextField(blank=True, null=True, verbose_name='Información adicional')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('popular', models.BooleanField(default=False, verbose_name='Lugar popular')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('direccion', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='lugar', to='lugares.direccion')),
            ],
            options={
                'verbose_name': 'Lugar',
                'verbose_name_plural': 'Lugares',
                'db_table': 'lugar',
                'ordering': ['nombre'],
            },
        ),
    ]
