# Generated by Django 5.1.9 on 2025-07-11 16:32

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PagoStripe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pedido', models.CharField(help_text='Número de pedido único interno', max_length=50, unique=True)),
                ('stripe_payment_intent_id', models.CharField(help_text='ID del Payment Intent de Stripe', max_length=255, unique=True)),
                ('stripe_charge_id', models.CharField(blank=True, help_text='ID del Charge de Stripe (después de confirmación)', max_length=255, null=True)),
                ('importe', models.DecimalField(decimal_places=2, help_text='Importe del pago en euros', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('moneda', models.CharField(default='EUR', help_text='Código de moneda ISO', max_length=3)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROCESANDO', 'Procesando'), ('COMPLETADO', 'Completado'), ('FALLIDO', 'Fallido'), ('CANCELADO', 'Cancelado'), ('REEMBOLSADO', 'Reembolsado'), ('REEMBOLSO_PARCIAL', 'Reembolso Parcial')], default='PENDIENTE', max_length=20)),
                ('tipo_pago', models.CharField(choices=[('INICIAL', 'Pago Inicial'), ('DIFERENCIA', 'Pago de Diferencia'), ('EXTRA', 'Pago Extra'), ('PENALIZACION', 'Penalización')], default='INICIAL', help_text='Tipo de pago dentro del flujo de reserva', max_length=20)),
                ('stripe_client_secret', models.CharField(help_text='Client secret para confirmación en frontend', max_length=255)),
                ('stripe_status', models.CharField(blank=True, help_text='Estado reportado por Stripe', max_length=50, null=True)),
                ('stripe_metadata', models.JSONField(default=dict, help_text='Metadatos adicionales de Stripe')),
                ('metodo_pago', models.CharField(blank=True, help_text='Método de pago usado (card, sepa_debit, etc.)', max_length=50, null=True)),
                ('ultimos_4_digitos', models.CharField(blank=True, help_text='Últimos 4 dígitos de la tarjeta', max_length=4, null=True)),
                ('marca_tarjeta', models.CharField(blank=True, help_text='Marca de la tarjeta (visa, mastercard, etc.)', max_length=20, null=True)),
                ('importe_reembolsado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Importe total reembolsado', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('datos_reserva', models.JSONField(default=dict, help_text='Datos completos de la reserva en formato JSON')),
                ('email_cliente', models.EmailField(help_text='Email del cliente para el pago', max_length=254)),
                ('nombre_cliente', models.CharField(help_text='Nombre completo del cliente', max_length=255)),
                ('mensaje_error', models.TextField(blank=True, help_text='Mensaje de error en caso de fallo', null=True)),
                ('codigo_error_stripe', models.CharField(blank=True, help_text='Código de error específico de Stripe', max_length=100, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_confirmacion', models.DateTimeField(blank=True, help_text='Fecha de confirmación del pago', null=True)),
                ('fecha_vencimiento', models.DateTimeField(blank=True, help_text='Fecha de vencimiento del Payment Intent', null=True)),
            ],
            options={
                'verbose_name': 'Pago Stripe',
                'verbose_name_plural': 'Pagos Stripe',
                'db_table': 'pagos_stripe',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ReembolsoStripe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_refund_id', models.CharField(help_text='ID del reembolso en Stripe', max_length=255, unique=True)),
                ('importe', models.DecimalField(decimal_places=2, help_text='Importe del reembolso', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('motivo', models.CharField(choices=[('CANCELACION_CLIENTE', 'Cancelación por Cliente'), ('CANCELACION_EMPRESA', 'Cancelación por Empresa'), ('MODIFICACION_RESERVA', 'Modificación de Reserva'), ('ERROR_PAGO', 'Error en el Pago'), ('FRAUDE', 'Fraude'), ('OTRO', 'Otro Motivo')], default='CANCELACION_CLIENTE', max_length=30)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROCESANDO', 'Procesando'), ('COMPLETADO', 'Completado'), ('FALLIDO', 'Fallido'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del motivo del reembolso', null=True)),
                ('stripe_status', models.CharField(blank=True, max_length=50, null=True)),
                ('stripe_failure_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_procesamiento', models.DateTimeField(blank=True, help_text='Fecha en que se procesó el reembolso', null=True)),
            ],
            options={
                'verbose_name': 'Reembolso Stripe',
                'verbose_name_plural': 'Reembolsos Stripe',
                'db_table': 'reembolsos_stripe',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='WebhookStripe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_event_id', models.CharField(help_text='ID único del evento de Stripe', max_length=255, unique=True)),
                ('tipo_evento', models.CharField(help_text='Tipo de evento (payment_intent.succeeded, etc.)', max_length=100)),
                ('procesado', models.BooleanField(default=False, help_text='Indica si el webhook fue procesado exitosamente')),
                ('datos_evento', models.JSONField(help_text='Datos completos del evento de Stripe')),
                ('fecha_recepcion', models.DateTimeField(auto_now_add=True)),
                ('fecha_procesamiento', models.DateTimeField(blank=True, null=True)),
                ('intentos_procesamiento', models.PositiveIntegerField(default=0)),
                ('mensaje_error', models.TextField(blank=True, help_text='Mensaje de error si el procesamiento falló', null=True)),
            ],
            options={
                'verbose_name': 'Webhook Stripe',
                'verbose_name_plural': 'Webhooks Stripe',
                'db_table': 'webhooks_stripe',
                'ordering': ['-fecha_recepcion'],
            },
        ),
    ]
