# Generated by Django 5.1.9 on 2025-05-22 19:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoRedsys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pedido', models.CharField(help_text='Número de pedido único para Redsys', max_length=50, unique=True)),
                ('importe', models.DecimalField(decimal_places=2, help_text='Importe del pago en euros', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPLETADO', 'Completado'), ('FALLIDO', 'Fallido'), ('ANULADO', 'Anulado')], default='PENDIENTE', max_length=20)),
                ('merchant_parameters', models.TextField(blank=True, help_text='Parámetros codificados enviados a Redsys', null=True)),
                ('signature', models.CharField(blank=True, help_text='Firma generada para Redsys', max_length=255, null=True)),
                ('codigo_autorizacion', models.CharField(blank=True, help_text='Código de autorización de Redsys', max_length=20, null=True)),
                ('codigo_respuesta', models.CharField(blank=True, help_text='Código de respuesta de Redsys', max_length=10, null=True)),
                ('mensaje_error', models.TextField(blank=True, help_text='Mensaje de error en caso de fallo', null=True)),
                ('datos_reserva', models.JSONField(default=dict, help_text='Datos completos de la reserva en formato JSON')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('reserva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_redsys', to='api.reserva')),
            ],
            options={
                'verbose_name': 'Pago Redsys',
                'verbose_name_plural': 'Pagos Redsys',
                'db_table': 'pagos_redsys',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
