# Generated by Django 5.1.9 on 2025-06-22 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagostripe',
            name='reserva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_stripe', to='reservas.reserva'),
        ),
        migrations.AddField(
            model_name='reembolsostripe',
            name='pago_stripe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reembolsos', to='payments.pagostripe'),
        ),
        migrations.AddIndex(
            model_name='pagostripe',
            index=models.Index(fields=['stripe_payment_intent_id'], name='pagos_strip_stripe__7bbc56_idx'),
        ),
        migrations.AddIndex(
            model_name='pagostripe',
            index=models.Index(fields=['numero_pedido'], name='pagos_strip_numero__d8a384_idx'),
        ),
        migrations.AddIndex(
            model_name='pagostripe',
            index=models.Index(fields=['estado', 'fecha_creacion'], name='pagos_strip_estado_09c608_idx'),
        ),
        migrations.AddIndex(
            model_name='pagostripe',
            index=models.Index(fields=['reserva', 'tipo_pago'], name='pagos_strip_reserva_1ee2a4_idx'),
        ),
    ]
