# Generated by Django 5.1.9 on 2025-06-22 13:29

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PoliticaPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('deductible', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Deductible')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Política de Pago',
                'verbose_name_plural': 'Políticas de Pago',
                'db_table': 'politica_pago',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('descuento_pct', models.DecimalField(decimal_places=2, help_text='Porcentaje de descuento (1.00 = 1%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Descuento (%)')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de fin')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Promoción',
                'verbose_name_plural': 'Promociones',
                'db_table': 'promocion',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='TipoPenalizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del tipo de penalización p.e cancelación | devolución tardía | recogida tardía | etc.', max_length=100, unique=True, verbose_name='Nombre')),
                ('tipo_tarifa', models.CharField(choices=[('porcentaje', 'Porcentaje'), ('fijo', 'Fijo'), ('importe_dia', 'Importe por día')], help_text='Tipo de tarifa para calcular la penalización', max_length=20, verbose_name='Tipo de tarifa')),
                ('valor_tarifa', models.DecimalField(decimal_places=2, help_text='Valor en euros o porcentaje según el tipo de tarifa', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor de la tarifa')),
            ],
            options={
                'verbose_name': 'Tipo de Penalización',
                'verbose_name_plural': 'Tipos de Penalización',
                'db_table': 'tipo_penalizacion',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PoliticaIncluye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255, verbose_name='Item')),
                ('incluye', models.BooleanField(default=True, verbose_name='Incluye')),
                ('politica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='politicas.politicapago')),
            ],
            options={
                'verbose_name': 'Item Incluido',
                'verbose_name_plural': 'Items Incluidos',
                'db_table': 'politica_incluye',
                'unique_together': {('politica', 'item')},
            },
        ),
        migrations.CreateModel(
            name='PoliticaPenalizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_previas', models.PositiveIntegerField(help_text='Número de horas previas al evento para aplicar esta penalización', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8760)], verbose_name='Horas previas')),
                ('politica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalizaciones', to='politicas.politicapago')),
                ('tipo_penalizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='politicas', to='politicas.tipopenalizacion')),
            ],
            options={
                'verbose_name': 'Penalización de Política',
                'verbose_name_plural': 'Penalizaciones de Política',
                'db_table': 'politica_penalizacion',
                'unique_together': {('politica', 'tipo_penalizacion')},
            },
        ),
    ]
