# Generated by Django 5.1.9 on 2025-06-25 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politicas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='politicapago',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
