# Generated by Django 5.1.9 on 2025-07-11 16:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('asunto', models.CharField(max_length=200, verbose_name='Asunto')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('resuelto', 'Resuelto'), ('cerrado', 'Cerrado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de respuesta')),
                ('respuesta', models.TextField(blank=True, verbose_name='Respuesta')),
                ('respondido_por', models.CharField(blank=True, max_length=100, verbose_name='Respondido por')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
            ],
            options={
                'verbose_name': 'Mensaje de contacto',
                'verbose_name_plural': 'Mensajes de contacto',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('blog', 'Blog'), ('faq', 'FAQ'), ('legal', 'Legal'), ('info', 'Información'), ('mini_section', 'Sección mínima'), ('testimonial', 'Testimonio')], max_length=20, verbose_name='Tipo')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('subtitulo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Subtítulo')),
                ('cuerpo', models.TextField(blank=True, null=True, verbose_name='Cuerpo')),
                ('info_adicional', models.JSONField(blank=True, null=True, verbose_name='Información adicional')),
                ('icono_url', models.CharField(blank=True, max_length=200, null=True, verbose_name='Icono')),
                ('activo', models.BooleanField(default=False, verbose_name='Activo')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Contenido',
                'verbose_name_plural': 'Contenidos',
                'db_table': 'contenido',
                'ordering': ['tipo', 'titulo'],
                'indexes': [models.Index(fields=['tipo', 'activo'], name='contenido_tipo_17a18a_idx')],
            },
        ),
    ]
